production:
  adapter: mysql
  encoding: utf8
  database: oscoursedesign
  pool: 5
  host: localhost
  username: root
  password: loveyiran1314
  timeout: 5000
test:
  adapter: mysql
  encoding: utf8
  database: oscoursedesign
  pool: 5
  host: localhost
  username: root
  password: loveyiran1314
  timeout: 5000
development:
  adapter: mysql
  encoding: utf8
  database: oscoursedesign
  pool: 5
  host: localhost
  username: root
  password: loveyiran1314
  timeout: 5000